Repository elastic/elastic-agent-system-metrics, pull requests merged in 2022-07, with the labels that each got.

#40 Add IsZero to CPU Totals, report value for monitoring
  CHANGELOG.md
  metric/system/process/helpers.go
  metric/system/process/process.go
  metric/system/process/process_test.go
  metric/system/process/process_types.go
Labels: bug, Team:Elastic-Agent-Data-Plane, v8.4.0, v8.3.0

#42 [automation] Update go release version 1.17.12
  .go-version
  .golangci.yml
Labels: automation, dependency

#43 fix thread safety in process code
  CHANGELOG.md
  metric/system/process/process.go
  metric/system/process/process_common.go
  metric/system/process/process_linux_common.go
  metric/system/process/process_test.go
  report/metrics_report_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, v8.3.0

#44 Add changelog for v0.4.4
  CHANGELOG.md
Labels: bug, Team:Elastic-Agent-Data-Plane

#45 [automation] Update go release version 1.18.4
  .go-version
  .golangci.yml
Labels: automation, dependency
