Repository elastic/elastic-agent-system-metrics, pull requests merged in 2022-06, with the labels that each got.

#32 Add uninterruptible disk sleep to system/process metrics
  CHANGELOG.md
  metric/system/process/process_common.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#35 Synchronize lint rules across repositories
  .golangci.yml
  dev-tools/templates/.golangci.yml
Labels: Team:Elastic-Agent-Data-Plane

#36 Pick changes from https://github.com/elastic/beats/pull/31643 to add support for CPU info
  CHANGELOG.md
  metric/cpu/metrics.go
  metric/cpu/metrics_linux.go
  metric/cpu/metrics_linux_test.go
  metric/cpu/metrics_procfs_common.go
  metric/cpu/testdata/cpuinfo
  metric/cpu/testdata/cpuinfo-armv7
  metric/cpu/testdata/cpuinfo-armv7.expected.json
  metric/cpu/testdata/cpuinfo-quad-socket
  metric/cpu/testdata/cpuinfo-quad-socket.expected.json
  metric/cpu/testdata/cpuinfo.expected.json
Labels: Team:Elastic-Agent-Data-Plane

#37 Move registry used by handles processor
  report/setup.go
Labels: bug, Team:Elastic-Agent-Data-Plane
