Repository elastic/elastic-agent-system-metrics, pull requests merged in 2022-09, with the labels that each got.

#39 ci: enable orka m1 builds
  .ci/Jenkinsfile
Labels: Team:Automation, automation

#52 [automation] Update go release version 1.18.6
  .go-version
  .golangci.yml
Labels: automation, dependency

#54 Make process package buildable on AIX
  CHANGELOG.md
  metric/system/process/process_aix.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#55 Move exported helpers to process_common.go file
  metric/system/process/process.go
  metric/system/process/process_common.go
Labels: Team:Elastic-Agent-Data-Plane
