Repository elastic/elastic-agent-system-metrics, pull requests merged in 2022-05, with the labels that each got.

#16 Add linux Hwmon reporting interface
  go.mod
  go.sum
  metric/system/hwmon/doc.go
  metric/system/hwmon/hwmon.go
  metric/system/hwmon/hwmon_test.go
  metric/system/hwmon/hwmon_types.go
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/name
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp1_crit
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp1_crit_alarm
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp1_input
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp1_label
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp1_max
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp2_crit
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp2_crit_alarm
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp2_input
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp2_label
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp2_max
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp3_crit
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp3_crit_alarm
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp3_input
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp3_label
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp3_max
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp4_crit
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp4_crit_alarm
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp4_input
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp4_label
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp4_max
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp5_crit
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp5_crit_alarm
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp5_input
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp5_label
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp5_max
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp6_crit
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp6_crit_alarm
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp6_input
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp6_label
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp6_max
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp7_crit
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp7_crit_alarm
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp7_input
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp7_label
  metric/system/hwmon/testdata/PoweredgeR720/sys/class/hwmon/hwmon0/temp7_max
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon3/in0_input
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon3/name
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/fan1_input
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/name
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/pwm1
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/pwm1_enable
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp1_input
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp1_label
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp2_input
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp2_label
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp3_input
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp4_input
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp5_input
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp6_input
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp7_input
  metric/system/hwmon/testdata/ThinkpadX250/sys/class/hwmon/hwmon4/temp8_input
Labels: Team:Elastic-Agent-Data-Plane

#17 Revert changes that removed filesystem code
  metric/system/filesystem/filesystem.go
  metric/system/filesystem/filesystem_darwin.go
  metric/system/filesystem/filesystem_test.go
  metric/system/filesystem/filesystem_unix.go
  metric/system/filesystem/filesystem_unix_common.go
  metric/system/filesystem/filesystem_windows.go
Labels: Team:Elastic-Agent-Data-Plane

#18 Fix build tags for `darwin` after refactoring of metrics handles
  metric/system/process/process.go
  metric/system/process/process_common.go
  metric/system/process/process_darwin.go
Labels: Team:Elastic-Agent-Data-Plane

#29 automation: bump golang version
  .ci/Jenkinsfile
  .ci/bump-go-release-version.sh
Labels: Team:Automation

#26 Fix issue with certain V1 cgroup events not reporting root IDs
  metric/system/cgroup/reader.go
  metric/system/cgroup/reader_test.go
  metric/system/cgroup/testdata/docker.zip
  metric/system/cgroup/testdata/ubuntu1804.zip
  metric/system/cgroup/util_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#30 [automation] Update go release version 1.17.10
  .go-version
  .golangci.yml
Labels: automation, dependency

#27 Move pacakges from Metricbeat: `internal/metrics/cpu` and `internal/metrics/memory`
  CHANGELOG.md
  NOTICE.txt
  go.mod
  go.sum
  metric/cpu/doc.go
  metric/cpu/metrics.go
  metric/cpu/metrics_aix.go
  metric/cpu/metrics_darwin.go
  metric/cpu/metrics_freebsd.go
  metric/cpu/metrics_linux.go
  metric/cpu/metrics_openbsd.go
  metric/cpu/metrics_procfs_common.go
  metric/cpu/metrics_test.go
  metric/cpu/metrics_windows.go
  metric/memory/memory.go
  metric/memory/memory_aix.go
  metric/memory/memory_darwin.go
  metric/memory/memory_freebsd.go
  metric/memory/memory_helpers.go
  metric/memory/memory_linux.go
  metric/memory/memory_openbsd.go
  metric/memory/memory_test.go
  metric/memory/memory_windows.go
  metric/memory/oldkern/proc/meminfo
Labels: Team:Elastic-Agent-Data-Plane
