Repository elastic/elastic-agent-system-metrics, pull requests merged in 2023-03, with the labels that each got.

#73 Linux process permission fix
  metric/system/process/process_linux_common.go
  metric/system/process/process_linux_test.go
Labels: Team:Elastic-Agent

#75 Make host metrics reporting FQDN-aware
  go.mod
  go.sum
  metric/system/host/host.go
Labels: enhancement

#77 Fix io.stat parsing errors
  metric/system/cgroup/cgv2/io.go
  metric/system/cgroup/cgv2/v2_test.go
  metric/system/cgroup/testdata/io_statfiles/ubuntu/io.stat
  metric/system/cgroup/testdata/io_statfiles/ubuntu2/io.stat
Labels: bug, Team:Elastic-Agent

#82 Move SetupInfoUserMetrics out of a cgo build constraint
  report/metrics_common.go
  report/setup.go
Labels: Team:Elastic-Agent
