Repository elastic/elastic-agent-system-metrics, pull requests merged in 2023-11, with the labels that each got.

#104 Fix metrics collection for privileged process on Windows
  metric/system/process/process.go
  metric/system/process/process_aix.go
  metric/system/process/process_darwin.go
  metric/system/process/process_linux_common.go
  metric/system/process/process_test.go
  metric/system/process/process_windows.go
  metric/system/process/process_windows_test.go
Labels: Team:Elastic-Agent

#103 reduce resource usage
  metric/system/cgroup/reader.go
  metric/system/cgroup/util.go
  metric/system/process/process_darwin.go
  metric/system/process/process_linux_common.go
  metric/system/process/process_windows.go
Labels: enhancement, Team:Elastic-Agent

#115 add PssFreeSnapshot
  metric/system/process/process_windows.go
  metric/system/process/syscall_windows.go
  metric/system/process/zsyscall_windows.go
Labels: bug, Team:Elastic-Agent

#114 Add metrics from /proc/[pid]/io to system/process metrics on linux
  CHANGELOG.md
  metric/system/process/process_linux_common.go
  metric/system/process/process_linux_test.go
  metric/system/process/process_types.go
  metric/system/process/testdata/proc/42/io
Labels: Team:Elastic-Agent

#116 metric/system: preallocate arrays
  metric/system/diskio/diskstat_windows_helper.go
  metric/system/process/process.go
  metric/system/process/process_darwin.go
  metric/system/process/process_linux_common.go
  metric/system/process/process_windows.go
Labels: Cleanup

#118 CI: fix linter config issue
  .github/workflows/golangci-lint.yml
Labels: bug, Team:Elastic-Agent

#119 CI: remove deprecated skip-go-install option
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: Cleanup

#120 Fix process metrics collection when both cgroup V1 and V2 controllers exist
  CHANGELOG.md
  metric/system/cgroup/reader_test.go
  metric/system/cgroup/testdata/amzn2.zip
  metric/system/cgroup/util.go
  metric/system/cgroup/util_test.go
Labels: bug, Team:Elastic-Agent

#121 Add metrics for disk reads and writes per cgroup
  CHANGELOG.md
  metric/system/cgroup/cgv1/blkio.go
  metric/system/cgroup/cgv1/blkio_test.go
  metric/system/cgroup/testdata/docker/sys/fs/cgroup/blkio/docker/b29faf21b7eff959f64b4192c34d5d67a707fe8561e9eaa608cb27693fba4242/blkio.throttle.io_service_bytes
  metric/system/cgroup/testdata/docker/sys/fs/cgroup/blkio/docker/b29faf21b7eff959f64b4192c34d5d67a707fe8561e9eaa608cb27693fba4242/blkio.throttle.io_serviced
Labels: enhancement, Team:Elastic-Agent
