Repository elastic/elastic-agent-system-metrics, pull requests merged in 2024-08, with the labels that each got.

#172 [system/process] add support for mutlierr
  metric/system/process/helper_test.go
  metric/system/process/helpers.go
  metric/system/process/helpers_others.go
  metric/system/process/helpers_windows.go
  metric/system/process/process.go
  metric/system/process/process_aix.go
  metric/system/process/process_container_test.go
  metric/system/process/process_darwin.go
  metric/system/process/process_linux_common.go
  metric/system/process/process_test.go
  metric/system/process/process_windows.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, breaking-change

#175 Change cgroups log line from `Infof` from `Debugf`
  metric/system/cgroup/util.go
Labels: bug

#176 fix non-fatal error tests
  metric/system/process/helpers.go
  metric/system/process/process.go
  metric/system/process/process_linux_test.go
  metric/system/process/process_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane
