Repository elastic/elastic-agent-system-metrics, pull requests merged in 2024-07, with the labels that each got.

#163 refactor: bump github.com/gofrs/uuid to current major version
  go.mod
  go.sum
  report/metrics_common.go
Labels: Team:Elastic-Agent-Data-Plane, Cleanup

#166 [system/process] add support for mutlierr
  metric/system/process/helper_test.go
  metric/system/process/helpers.go
  metric/system/process/helpers_others.go
  metric/system/process/helpers_windows.go
  metric/system/process/process.go
  metric/system/process/process_aix.go
  metric/system/process/process_container_test.go
  metric/system/process/process_darwin.go
  metric/system/process/process_linux_common.go
  metric/system/process/process_test.go
  metric/system/process/process_windows.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, breaking-change

#167 fix: move non-fatal error to helpers
  metric/system/process/helpers.go
  metric/system/process/process.go
Labels: Team:Elastic-Agent-Data-Plane

#169 Revert non fatal error changes for now.
  metric/system/process/helper_test.go
  metric/system/process/helpers.go
  metric/system/process/helpers_others.go
  metric/system/process/helpers_windows.go
  metric/system/process/process.go
  metric/system/process/process_aix.go
  metric/system/process/process_container_test.go
  metric/system/process/process_darwin.go
  metric/system/process/process_linux_common.go
  metric/system/process/process_test.go
  metric/system/process/process_windows.go
Labels: Team:Elastic-Agent-Data-Plane

#168 Comply with ECS for `host.name`
  NOTICE.txt
  go.mod
  go.sum
  metric/system/host/host.go
  metric/system/host/host_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#171 Update to docker v26.1.5
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane
