Repository elastic/elastic-agent-system-metrics, pull requests merged in 2024-04, with the labels that each got.

#134 Make cgroup errors skippable in system/process
  CHANGELOG.md
  metric/system/cgroup/util.go
  metric/system/process/process.go
  metric/system/process/process_linux_test.go
  metric/system/process/process_test.go
  metric/system/process/testdata/proc/cgroups
  metric/system/process/testdata/proc/self/mountinfo
Labels: bug, Team:Elastic-Agent

#138 upgraded go-sysinfo
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent

#140 Add a test framework for monitoring the host system from inside a container
  .buildkite/pipeline.yml
  .buildkite/scripts/system-container-tests.sh
  dev-tools/systemtests/container.go
  dev-tools/systemtests/testResolve.go
  go.mod
  go.sum
  metric/cpu/metrics_test.go
  metric/system/filesystem/filesystem_test.go
  metric/system/process/process_container_test.go
  metric/system/process/process_linux_test.go
  tests/container_system_mon_test.go
Labels: Team:Elastic-Agent

#146 Update some dependencies, change how go is installed in windows
  .buildkite/pipeline.yml
  .buildkite/scripts/run-win-tests.ps1
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, dependency
